@ApiHost = http://localhost:5162
@taskId = 1

POST {{ApiHost}}/api/tasks
Content-Type: application/json

{
  "title": "Learn HTTP status codes",
  "description": "Phase 0B in-memory API"
}

###

GET {{ApiHost}}/api/tasks

###

GET {{ApiHost}}/api/tasks/{{taskId}}

###

PUT {{ApiHost}}/api/tasks/{{taskId}}
Content-Type: application/json

{
  "title": "Understand HTTP status codes",
  "description": "Updated with PUT",
  "isCompleted": true
}

###

DELETE {{ApiHost}}/api/tasks/{{taskId}}

###

POST {{ApiHost}}/api/tasks
Content-Type: application/json

{
  "title": "   "
}

###

GET {{ApiHost}}/api/tasks/999999999
