$ErrorActionPreference = 'Stop'

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$project = Join-Path $repositoryRoot 'src/backend/FullStackOpsLab.Api/FullStackOpsLab.Api.csproj'

Push-Location $repositoryRoot
try {
    $contextInfo = dotnet ef dbcontext info --project $project --startup-project $project 2>&1
    if ($LASTEXITCODE -ne 0 -or ($contextInfo -join "`n") -notmatch 'AppDbContext') {
        throw 'EF Core did not discover AppDbContext.'
    }

    $script = dotnet ef dbcontext script --project $project --startup-project $project 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw 'EF Core could not generate the model SQL script.'
    }

    $sql = (($script -join "`n").Replace('"', '')).ToLowerInvariant()
    foreach ($pattern in @(
        'create table tasks\s*\(',
        'id integer generated by default as identity',
        'title text not null',
        'description text',
        'is_completed boolean not null',
        'created_at timestamp with time zone not null',
        'updated_at timestamp with time zone'
    )) {
        if ($sql -notmatch $pattern) {
            throw "Expected PostgreSQL model SQL pattern was missing: $pattern"
        }
    }

    if ($sql -match 'create table lab_tasks') {
        throw 'The application model must not create the Module 3B lab table.'
    }

    Write-Output 'Module 3D EF foundation smoke check passed: design-time context and tasks schema; no database writes.'
} finally {
    Pop-Location
}
